"""Pure canonical Program planning and deployment."""

from .deployment import build_program_deployment, build_program_manifest
from .parameters import (
    assign_parameter_slots,
    classify_parameter_use,
    dtype_and_shape,
    external_parameters,
    fragment_outputs,
    interface_by_location,
    internal_parameters,
    merge_internal_parameter_uses,
    merge_parameter_uses,
    reflected_parameters,
    validate_graphics_interfaces,
)
from .planner import build_program_plan
from .reflection import (
    compiled_stage_from_program,
    parse_reflection_json,
    select_artifact,
    select_artifact_bytes,
    select_entry,
)
from .serialize import (
    canonical_json,
    content_hash,
    inline_artifact_descriptor,
    serialize_bundle,
    with_content_hash,
)
from .types import (
    BundlePlan,
    CompiledArtifact,
    CompiledStage,
    CpuTargetOptions,
    CudaTargetOptions,
    DirectXTargetOptions,
    MetalTargetOptions,
    OpenGLESTargetOptions,
    OpenGLTargetOptions,
    ProgramCompileError,
    ProgramVariantPlan,
    TargetOptions,
    VulkanTargetOptions,
    make_target_options,
)

__all__ = [
    "BundlePlan",
    "CompiledArtifact",
    "CompiledStage",
    "CpuTargetOptions",
    "CudaTargetOptions",
    "DirectXTargetOptions",
    "MetalTargetOptions",
    "OpenGLESTargetOptions",
    "OpenGLTargetOptions",
    "ProgramCompileError",
    "TargetOptions",
    "ProgramVariantPlan",
    "VulkanTargetOptions",
    "assign_parameter_slots",
    "build_program_deployment",
    "build_program_manifest",
    "build_program_plan",
    "canonical_json",
    "classify_parameter_use",
    "compiled_stage_from_program",
    "content_hash",
    "dtype_and_shape",
    "external_parameters",
    "fragment_outputs",
    "inline_artifact_descriptor",
    "interface_by_location",
    "internal_parameters",
    "make_target_options",
    "merge_internal_parameter_uses",
    "merge_parameter_uses",
    "parse_reflection_json",
    "reflected_parameters",
    "select_artifact",
    "select_artifact_bytes",
    "select_entry",
    "serialize_bundle",
    "validate_graphics_interfaces",
    "with_content_hash",
]
