// Generated by tools/generate_versions.py from versions.toml. Do not edit.
#ifndef VERNON_VERSIONS_H
#define VERNON_VERSIONS_H

#define VERNON_RELEASE_VERSION "0.1.1a1"
#define VERNON_COMPILER_CONTRACT_VERSION 8
#define VERNON_PIPELINE_VERSION 11
#define VERNON_COMPILER_CONTRACT_VERSION_STRING "8"
#define VERNON_PIPELINE_VERSION_STRING "11"
#define VERNON_MLIR_VERSION_ATTRIBUTES "vernon.compiler_contract_version = 8 : i64, vernon.pipeline_version = 11 : i64"
#define VERNON_JSON_VERSION_FIELDS "\"compiler_contract_version\":8,\"pipeline_version\":11"
#define VERNON_PIPELINE_JSON_FIELD "\"pipeline_version\":11"

#endif // VERNON_VERSIONS_H
