"""Static Python DSL surface for the Vernon compiler.

The compiler reads source through :mod:`ast`; it never imports or executes the
input module. These Python objects exist for editor completion and type syntax.
"""

from typing import Annotated

from . import interop, storage
from .compiler import Compiler, compile_file, compile_source
from .decorators import fragment, func, kernel, struct, vertex
from .diagnostics import CompileError
from .intrinsics import (
    abs,
    clamp,
    cos,
    cross,
    dot,
    exp,
    fragment_coord,
    front_facing,
    instance_id,
    log,
    matmul,
    max,
    min,
    norm,
    normalize,
    pow,
    reflect,
    resolution,
    sin,
    sqrt,
    texture_sample,
    texture_size,
    vertex_id,
)
from .pipeline_assets import PipelineAssetDeclaration, pipeline_asset
from .runtime import (
    Kernel,
    Pipeline,
    PrimitiveTopology,
    TensorLayout,
    TensorStorage,
    TensorView,
    Texture,
    cpu,
    cuda,
    init,
    lines,
    opengl,
    opengles,
    pipeline,
    points,
    register_external_opengl_context,
    triangles,
    vulkan,
)
from .types import (
    Feature,
    Matrix,
    Sampler,
    Tensor,
    Tuple,
    Vector,
    When,
    bool,
    builtin,
    f16,
    f32,
    f64,
    feature,
    i32,
    instance,
    location,
    read,
    read_write,
    resource,
    u32,
    uniform,
    varying,
    write,
)

__all__ = [
    "Annotated",
    "abs",
    "CompileError",
    "Compiler",
    "Feature",
    "Kernel",
    "Matrix",
    "Pipeline",
    "PipelineAssetDeclaration",
    "PrimitiveTopology",
    "Sampler",
    "Tensor",
    "TensorLayout",
    "TensorStorage",
    "TensorView",
    "Texture",
    "Tuple",
    "When",
    "bool",
    "builtin",
    "clamp",
    "compile_file",
    "compile_source",
    "cos",
    "cpu",
    "cross",
    "cuda",
    "dot",
    "exp",
    "f16",
    "f32",
    "f64",
    "feature",
    "fragment",
    "fragment_coord",
    "front_facing",
    "func",
    "i32",
    "instance",
    "instance_id",
    "interop",
    "init",
    "location",
    "lines",
    "log",
    "kernel",
    "matmul",
    "max",
    "min",
    "norm",
    "normalize",
    "opengl",
    "opengles",
    "pow",
    "pipeline",
    "pipeline_asset",
    "points",
    "resource",
    "read",
    "read_write",
    "resolution",
    "reflect",
    "register_external_opengl_context",
    "sin",
    "sqrt",
    "storage",
    "struct",
    "texture_sample",
    "texture_size",
    "triangles",
    "u32",
    "uniform",
    "varying",
    "vertex",
    "vertex_id",
    "vulkan",
    "Vector",
    "write",
]
