"""Static Python DSL surface for the Vernon compiler.

The compiler reads source through :mod:`ast`; it never imports or executes the
input module. These Python objects exist for editor completion and type syntax.
"""

from typing import Annotated

from .compiler import Compiler, compile_file, compile_source
from .decorators import compute, fragment, kernel, struct, vertex
from .diagnostics import CompileError
from .intrinsics import abs, clamp, cos, cross, dot, exp, log, matmul, max, min, norm, normalize, pow, reflect, sin, sqrt, texture_sample
from .runtime import Kernel, Tensor, cpu, cuda, init
from .types import (
    Array,
    Buffer,
    Feature,
    Sampler,
    Texture,
    When,
    bool,
    builtin,
    f16,
    f32,
    f64,
    feature,
    i32,
    instance,
    location,
    mat,
    mat2,
    mat3,
    mat4,
    resource,
    u32,
    uniform,
    varying,
    vec,
    vec2,
    vec3,
    vec4,
)

__all__ = [
    "Annotated",
    "abs",
    "Array",
    "Buffer",
    "CompileError",
    "Compiler",
    "Feature",
    "Kernel",
    "Sampler",
    "Tensor",
    "Texture",
    "When",
    "bool",
    "builtin",
    "clamp",
    "compile_file",
    "compile_source",
    "compute",
    "cos",
    "cpu",
    "cross",
    "cuda",
    "dot",
    "exp",
    "f16",
    "f32",
    "f64",
    "feature",
    "fragment",
    "i32",
    "instance",
    "init",
    "location",
    "log",
    "kernel",
    "matmul",
    "mat",
    "mat2",
    "mat3",
    "mat4",
    "max",
    "min",
    "norm",
    "normalize",
    "pow",
    "resource",
    "reflect",
    "sin",
    "sqrt",
    "struct",
    "texture_sample",
    "u32",
    "uniform",
    "varying",
    "vec",
    "vec2",
    "vec3",
    "vec4",
    "vertex",
]
