from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "versions.toml"


def _rendered_files() -> dict[Path, str]:
    with MANIFEST.open("rb") as stream:
        values = tomllib.load(stream)["vernon"]

    release = str(values["release"])
    compiler_contract = int(values["compiler_contract"])
    pipeline = int(values["pipeline"])
    if compiler_contract <= 0 or pipeline <= 0:
        raise ValueError("contract versions must be positive")

    python = f'''# Generated by tools/generate_versions.py from versions.toml. Do not edit.

RELEASE_VERSION = "{release}"
COMPILER_CONTRACT_VERSION = {compiler_contract}
PIPELINE_VERSION = {pipeline}
'''
    header = f"""// Generated by tools/generate_versions.py from versions.toml. Do not edit.
#ifndef VERNON_VERSIONS_H
#define VERNON_VERSIONS_H

#define VERNON_RELEASE_VERSION "{release}"
#define VERNON_COMPILER_CONTRACT_VERSION {compiler_contract}
#define VERNON_PIPELINE_VERSION {pipeline}
#define VERNON_COMPILER_CONTRACT_VERSION_STRING "{compiler_contract}"
#define VERNON_PIPELINE_VERSION_STRING "{pipeline}"
#define VERNON_MLIR_VERSION_ATTRIBUTES \\
    "vernon.compiler_contract_version = {compiler_contract} : i64, vernon.pipeline_version = {pipeline} : i64"
#define VERNON_JSON_VERSION_FIELDS \\
    "\\"compiler_contract_version\\":{compiler_contract},\\"pipeline_version\\":{pipeline}"
#define VERNON_PIPELINE_JSON_FIELD "\\"pipeline_version\\":{pipeline}"

#endif // VERNON_VERSIONS_H
"""
    cmake = f"""# Generated by tools/generate_versions.py from versions.toml. Do not edit.
set(VERNON_RELEASE_VERSION "{release}")
set(VERNON_COMPILER_CONTRACT_VERSION {compiler_contract})
set(VERNON_PIPELINE_VERSION {pipeline})
"""
    rendered = {
        ROOT / "python/vernon_dsl/_versions.py": python,
        ROOT / "source/include/VernonVersions.h": header,
        ROOT / "cmake/VernonVersions.cmake": cmake,
        ROOT / "source/lib/runtime/VERSION": f"{release}\n",
    }
    for path in (ROOT / "source/tests/integration").glob("*.mlir"):
        fixture = path.read_text(encoding="utf-8")
        fixture = re.sub(
            r"vernon\.compiler_contract_version = \d+ : i64",
            f"vernon.compiler_contract_version = {compiler_contract} : i64",
            fixture,
        )
        fixture = re.sub(
            r"vernon\.pipeline_version = \d+ : i64",
            f"vernon.pipeline_version = {pipeline} : i64",
            fixture,
        )
        rendered[path] = fixture
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    stale: list[Path] = []
    for path, expected in _rendered_files().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")

    if stale:
        print("stale generated version files:", file=sys.stderr)
        for path in stale:
            print(f"  {path.as_posix()}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
