from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "versions.toml"


def _rendered_files() -> dict[Path, str]:
    with MANIFEST.open("rb") as stream:
        values = tomllib.load(stream)["vernon"]

    release = str(values["release"])
    release_match = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)(?:(?:a|b|rc)\d+)?", release)
    if release_match is None:
        raise ValueError("release must be a PEP 440 X.Y.Z or X.Y.Z prerelease")
    project_version = ".".join(release_match.groups())
    compiler_contract = int(values["compiler_contract"])
    program = int(values["program"])
    if compiler_contract <= 0 or program <= 0:
        raise ValueError("contract versions must be positive")

    mlir_version_macro = (
        '#define VERNON_MLIR_VERSION_ATTRIBUTES "'
        f"vernon.compiler_contract_version = {compiler_contract} : i64, "
        f'vernon.program_version = {program} : i64"\n'
    )
    json_version_macro = (
        '#define VERNON_JSON_VERSION_FIELDS "'
        f'\\"compiler_contract_version\\":{compiler_contract},'
        f'\\"program_version\\":{program}"\n'
    )
    python = f'''# Generated by tools/generate_versions.py from versions.toml. Do not edit.

RELEASE_VERSION = "{release}"
COMPILER_CONTRACT_VERSION = {compiler_contract}
PROGRAM_VERSION = {program}
'''
    header = f"""// Generated by tools/generate_versions.py from versions.toml. Do not edit.
#ifndef VERNON_VERSIONS_H
#define VERNON_VERSIONS_H

#define VERNON_RELEASE_VERSION "{release}"
#define VERNON_COMPILER_CONTRACT_VERSION {compiler_contract}
#define VERNON_PROGRAM_VERSION {program}
#define VERNON_COMPILER_CONTRACT_VERSION_STRING "{compiler_contract}"
#define VERNON_PROGRAM_VERSION_STRING "{program}"
{mlir_version_macro}{json_version_macro}\
#define VERNON_PROGRAM_JSON_FIELD "\\"program_version\\":{program}"

#endif // VERNON_VERSIONS_H
"""
    cmake = f"""# Generated by tools/generate_versions.py from versions.toml. Do not edit.
set(VERNON_RELEASE_VERSION "{release}")
set(VERNON_PROJECT_VERSION "{project_version}")
set(VERNON_COMPILER_CONTRACT_VERSION {compiler_contract})
set(VERNON_PROGRAM_VERSION {program})
"""
    rendered = {
        ROOT / "python/vernon_dsl/_versions.py": python,
        ROOT / "source/include/VernonVersions.h": header,
        ROOT / "cmake/VernonVersions.cmake": cmake,
        ROOT / "source/lib/runtime/VERSION": f"{release}\n",
    }
    for path in (ROOT / "source/tests/mlir").rglob("*.mlir"):
        fixture = path.read_text(encoding="utf-8")
        fixture = re.sub(
            r"vernon\.compiler_contract_version = \d+ : i64",
            f"vernon.compiler_contract_version = {compiler_contract} : i64",
            fixture,
        )
        fixture = re.sub(
            r"vernon\.(?:pipeline|program)_version = \d+ : i64",
            f"vernon.program_version = {program} : i64",
            fixture,
        )
        rendered[path] = fixture
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    stale: list[Path] = []
    for path, expected in _rendered_files().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")

    if stale:
        print("stale generated version files:", file=sys.stderr)
        for path in stale:
            print(f"  {path.as_posix()}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
