include_guard(GLOBAL)

function(vernon_add_tests)
    if(NOT BUILD_TESTING)
        return()
    endif()
    get_property(_vernon_tests_added GLOBAL PROPERTY VERNON_TESTS_ADDED)
    if(_vernon_tests_added)
        return()
    endif()
    if(NOT EXISTS "${VERNON_REPOSITORY_ROOT}/source/tests/CMakeLists.txt")
        message(FATAL_ERROR "Cannot locate VernonDSL tests")
    endif()
    set_property(GLOBAL PROPERTY VERNON_TESTS_ADDED TRUE)
    add_subdirectory("${VERNON_REPOSITORY_ROOT}/source/tests" "${CMAKE_CURRENT_BINARY_DIR}/tests")
endfunction()
