# Generated by tools/generate_versions.py from versions.toml. Do not edit.
set(VERNON_RELEASE_VERSION "0.2.0")
set(VERNON_PROJECT_VERSION "0.2.0")
set(VERNON_COMPILER_CONTRACT_VERSION 14)
set(VERNON_PIPELINE_VERSION 18)
