# Generated by tools/generate_versions.py from versions.toml. Do not edit.
set(VERNON_RELEASE_VERSION "0.1.2")
set(VERNON_PROJECT_VERSION "0.1.2")
set(VERNON_COMPILER_CONTRACT_VERSION 11)
set(VERNON_PIPELINE_VERSION 15)
